{-# LANGUAGE LambdaCase #-}

module HStream.SQL.Internal.Functor where

import           HStream.SQL.Abs

getScalarFuncValueExpr :: ScalarFunc -> [ValueExpr]
getScalarFuncValueExpr = \case
  ScalarFuncFieldToJson _ x y   -> [x, y]
  ScalarFuncFieldToText _ x y   -> [x, y]
  ScalarFuncFieldsToJson _ x y  -> [x, y]
  ScalarFuncFieldsToTexts _ x y -> [x, y]
  ScalarFuncSin _ x             -> [x]
  ScalarFuncSinh _ x            -> [x]
  ScalarFuncAsin _ x            -> [x]
  ScalarFuncAsinh _ x           -> [x]
  ScalarFuncCos _ x             -> [x]
  ScalarFuncCosh _ x            -> [x]
  ScalarFuncAcos _ x            -> [x]
  ScalarFuncAcosh _ x           -> [x]
  ScalarFuncTan _ x             -> [x]
  ScalarFuncTanh _ x            -> [x]
  ScalarFuncAtan _ x            -> [x]
  ScalarFuncAtanh _ x           -> [x]
  ScalarFuncAbs _ x             -> [x]
  ScalarFuncCeil _ x            -> [x]
  ScalarFuncFloor _ x           -> [x]
  ScalarFuncRound _ x           -> [x]
  ScalarFuncSign _ x            -> [x]
  ScalarFuncSqrt _ x            -> [x]
  ScalarFuncLog _ x             -> [x]
  ScalarFuncLog2 _ x            -> [x]
  ScalarFuncLog10 _ x           -> [x]
  ScalarFuncExp _ x             -> [x]
  ScalarFuncIsInt _ x           -> [x]
  ScalarFuncIsFloat _ x         -> [x]
  ScalarFuncIsNum _ x           -> [x]
  ScalarFuncIsBool _ x          -> [x]
  ScalarFuncIsStr _ x           -> [x]
  ScalarFuncIsArr _ x           -> [x]
  ScalarFuncIsDate _ x          -> [x]
  ScalarFuncIsTime _ x          -> [x]
  ScalarFuncToStr _ x           -> [x]
  ScalarFuncToLower _ x         -> [x]
  ScalarFuncToUpper _ x         -> [x]
  ScalarFuncTrim _ x            -> [x]
  ScalarFuncLTrim _ x           -> [x]
  ScalarFuncRTrim _ x           -> [x]
  ScalarFuncRev _ x             -> [x]
  ScalarFuncStrlen _ x          -> [x]
  ScalarFuncIfNull _ x y        -> [x, y]
  ScalarFuncNullIf _ x y        -> [x, y]
  ScalarFuncDateStr _ x y       -> [x, y]
  ScalarFuncStrDate _ x y       -> [x, y]
  ScalarFuncSplit _ x y         -> [x, y]
  ScalarFuncChunksOf _ x y      -> [x, y]
  ScalarFuncTake _ x y          -> [x, y]
  ScalarFuncTakeEnd _ x y       -> [x, y]
  ScalarFuncDrop _ x y          -> [x, y]
  ScalarFuncDropEnd _ x y       -> [x, y]
  ArrayFuncContain _ x y        -> [x, y]
  ArrayFuncDistinct _ x         -> [x]
  ArrayFuncExcept _ x y         -> [x, y]
  ArrayFuncIntersect _ x y      -> [x, y]
  ArrayFuncLength _ x           -> [x]
  ArrayFuncRemove _ x y         -> [x, y]
  ArrayFuncUnion _ x y          -> [x, y]
  ArrayFuncJoin _ x             -> [x]
  ArrayFuncJoinWith _ x y       -> [x, y]
  ArrayFuncMax _ x              -> [x]
  ArrayFuncMin _ x              -> [x]
  ArrayFuncSort _ x             -> [x]
