# This is a configmap generator for the cluster config. It will get mounted
# to the daemon as a file that gets automatically updated when the config map
# content changes.
configMapGenerator:
  - name: logdevice-config
    files:
      - config.json
resources:
  - logdevice-statefulset.yaml
  - logdevice-service.yaml
  - logdevice-admin-server.yaml
  - hstream-server.yaml
generatorOptions:
  disableNameSuffixHash: true
