FROM hstreamdb/haskell:9.2

ARG CABAL_MIRROR_NAME="hackage.haskell.org"
ARG CABAL_MIRROR_URL="http://hackage.haskell.org/"

RUN cabal user-config init && echo "\
repository $CABAL_MIRROR_NAME \n\
  url: $CABAL_MIRROR_URL \n\
" > /root/.cabal/config && cabal user-config update && \
    cabal update

COPY . /hstream
RUN cd /hstream && make all && \
    cabal build --enable-tests --enable-benchmarks all && \
    rm -rf /hstream

# vim: set ft=dockerfile:
