apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hstream.fullname" . }}-logdevice-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hstream.labels" . | nindent 4 }}
data:
  "config.json": |
    {
      "server_settings": {
        "enable-nodes-configuration-manager": "true",
        "use-nodes-configuration-manager-nodes-configuration": "true",
        "enable-node-self-registration": "true",
        "enable-cluster-maintenance-state-machine": "true"
      },
      "client_settings": {
        "enable-nodes-configuration-manager": "true",
        "use-nodes-configuration-manager-nodes-configuration": "true",
        "admin-client-capabilities": "true"
      },
      "cluster": "logdevice",
      "internal_logs": {
        "config_log_deltas": {
          "replicate_across": {
            "node": {{ .Values.logdevice.replicateAcross | int }}
          }
        },
        "config_log_snapshots": {
          "replicate_across": {
            "node":  {{ .Values.logdevice.replicateAcross | int }}
          }
        },
        "event_log_deltas": {
          "replicate_across": {
            "node":  {{ .Values.logdevice.replicateAcross | int }}
          }
        },
        "event_log_snapshots": {
          "replicate_across": {
            "node":  {{ .Values.logdevice.replicateAcross | int }}
          }
        },
        "maintenance_log_deltas": {
          "replicate_across": {
            "node":  {{ .Values.logdevice.replicateAcross | int }}
          }
        },
        "maintenance_log_snapshots": {
          "replicate_across": {
            "node":  {{ .Values.logdevice.replicateAcross | int }}
          }
        }
      },
      "metadata_logs": {
        "nodeset": [],
        "replicate_across": {
          "node":  {{ .Values.logdevice.replicateAcross | int }}
        }
      },
      "zookeeper": {
        "zookeeper_uri": "ip://{{ include "hstream.zookeeper.uri" . }}",
        "timeout": "30s"
      }
    }
