name: Publish latest

on:
  push:
    branches: [master, main]

env:
  IMAGE_NAME: "hstreamdb/hstream"
  DEPS_IMAGE_NAME: "hstreamdb/hstream-builder"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Push image to dockerhub
        run: |
          echo "Build & Push ${IMAGE_NAME}..."
          docker build . --build-arg BUILDER_IMAGE=${DEPS_IMAGE_NAME} -t ${IMAGE_NAME}:latest

          if [ -n "${{ secrets.DOCKERHUB_USERNAME }}" -a -n "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "Login dockerhub..."
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            docker push ${IMAGE_NAME}:latest

            curl \
              -X POST \
              -H 'Accept: application/vnd.github.v3+json' \
              -u ${{ secrets.PERSONAL_ACCESS_TOKEN }} \
              ${{ secrets.DISPATCH_URL }} \
              --data '{"event_type": "image_updated", "client_payload": { "tag": "latest" }}'
          else
            echo "Empty dockerhub user info..."
          fi
