name: Publish latest

on:
  push:
    branches: [master, main]

env:
  IMAGE_NAME: "hstreamdb/hstream"
  DEPS_IMAGE_NAME: "hstreamdb/hstream-builder"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Docker build
        run: docker build . --build-arg BUILDER_IMAGE=${DEPS_IMAGE_NAME} -t ${IMAGE_NAME}:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to dockerhub
        run: docker push ${IMAGE_NAME}:latest

      - name: Trigger testing ci
        run: |
          curl -X POST \
              -H 'Accept: application/vnd.github.v3+json' \
              -u ${{ secrets.PERSONAL_ACCESS_TOKEN }} \
              ${{ secrets.DISPATCH_URL }} \
              --data '{"event_type": "image_updated", "client_payload": { "tag": "latest" }}'
