name: Publish builder

on:
  push:
    branches: [master, main]

env:
  IMAGE_NAME: "hstreamdb/hstream-builder"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        hs_tag: ["latest", "rqlite_8.10.7"]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Build
        run: |
          docker build . -f docker/Dockerfile.deps --build-arg HS_TAG=${{ matrix.hs_tag }} -t ${IMAGE_NAME}:${{ matrix.hs_tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to dockerhub
        run: docker push ${IMAGE_NAME}:${{ matrix.hs_tag }}
