name: Publish latest

on:
  push:
    branches: [master, main]

env:
  IMAGE_NAME: "hstreamdb/hstream"
  DEPS_IMAGE_NAME: "hstreamdb/hstream-builder"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: "recursive"

      - name: Docker build
        run: docker build . -f docker/Dockerfile --build-arg BUILDER_IMAGE=${DEPS_IMAGE_NAME} -t ${IMAGE_NAME}:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to dockerhub
        run: docker push ${IMAGE_NAME}:latest

      - name: Trigger testing ci
        run: |
          curl -X POST \
              -H 'Accept: application/vnd.github.v3+json' \
              -u ${{ secrets.PERSONAL_ACCESS_TOKEN }} \
              https://api.github.com/repos/hstreamdb/integration-tests/dispatches \
              --data "{\"event_type\": \"image_updated\", \"client_payload\": { \"tag\": \"latest\", \"commit_sha\": \"$GITHUB_SHA\" }}"

      - name: Trigger jepsen test ci
        run: |
          curl -X POST \
              -H 'Accept: application/vnd.github.v3+json' \
              -u ${{ secrets.PERSONAL_ACCESS_TOKEN }} \
              https://api.github.com/repos/hstreamdb/jepsen.hstream/dispatches \
              --data "{\"event_type\": \"image_updated\", \"client_payload\": { \"tag\": \"$TAG\", \"commit_sha\": \"$GITHUB_SHA\" }}"

      - name: Trigger bench ci
        run: |
          curl -X POST \
              -H 'Accept: application/vnd.github.v3+json' \
              -u ${{ secrets.PERSONAL_ACCESS_TOKEN }} \
              https://api.github.com/repos/hstreamdb/bench/dispatches \
              --data "{\"event_type\": \"image_updated\", \"client_payload\": { \"tag\": \"latest\", \"commit_sha\": \"$GITHUB_SHA\" }}"
