name: Publish builder

on:
  push:
    branches: [master, main]

env:
  DEPS_IMAGE_NAME: "hstreamdb/hstream-builder"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"

      - name: Build
        run: |
          docker build . -f docker/Dockerfile.deps -t ${DEPS_IMAGE_NAME}:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image to dockerhub
        run: docker push ${DEPS_IMAGE_NAME}:latest
