{
 "title": "HStream Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Subscription Send (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(subscription_send_out_bytes{instance=\"localhost:9270\", job=\"hstream\", type=\"send_out_bytes_10s\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscription Acks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "subscription_acks{instance=\"localhost:9270\", job=\"hstream\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Append (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(stream_append_in_bytes{instance=\"localhost:9270\", job=\"hstream\", type=\"append_in_bytes_10s\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Append Failed Num",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "stream_counter_append_failed{instance=\"localhost:9270\", job=\"hstream\", type=\"append_failed\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Subscription Response Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "subscription_response_messages{instance=\"localhost:9270\", type=\"response_messages_10s\", job=\"hstream\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Append Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "server_histogram_append_request_latency{instance=\"localhost:9270\", job=\"hstream\", server_histogram=\"server_histogram\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU used percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum by (group, instance, job) (100 - ((rate(node_cpu_seconds_total{mode=\"idle\"}[30s])) * 100))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory used percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes) * 100"
    }
   ]
  }
 ]
}